#!/bin/sh
[ -t 1 ] && {
    export CSI="$(printf '\033')["
    export RESET="${CSI}m"
    export BOLD="${CSI}1m"
    export FG_GREEN="${CSI}32m"
    export FG_RED="${CSI}31m"
    export FG_RED_B="${CSI}91m" # Bright
}

[ $# -eq 0 ] || [ "$1" = help ] && {
    NAME="$(basename "$0")"
    echo "${NAME} ${BOLD}save${RESET} -- Save current settings to repo"
    echo "${NAME} ${BOLD}load${RESET} -- Load settings from repo"
    echo "${NAME} ${BOLD}help${RESET} -- Print this help"
    [ $# -gt 0 ]; exit $?   # Clever, isn't it?
}

cd "$(dirname "$0")"
touch stdout stderr; chmod 0600 stdout stderr
trap 'rm -f stdout stderr' EXIT INT HUP TERM

if [ "$1" = "dry_${1#dry_}" ]
then run() { printf '%s\n' "$*"; }
else
    if [ ! -t 1 ]
    then run() { printf '%s\n' "$*"; "$@"; }
    else run() {
            printf '[    ] %s' "$*"
            "$@" 1>stdout 2>stderr
            if [ $? -eq 0 ]; then
                printf "${CSI}$(( ${#*} + 6 ))D${FG_GREEN} %s ${RESET}"'\n' OK
            else
                printf "${CSI}$(( ${#*} + 6 ))D${BOLD}${FG_RED_B}%s${RESET}"'\n' FAIL
                cat stderr
            fi
        }
    fi
fi

_save() {
    run rm -rf home

    run mkdir           home
    run cp ~/.shrc      home
    run cp ~/.zshrc     home
    run cp ~/.vimrc     home
    run cp ~/.profile   home
    run cp ~/.gitconfig home
    run cp -R ~/.zsh    home

    run mkdir                   home/.ssh
    run cp -R ~/.ssh/config     home/.ssh

    run mkdir                       home/.config
    run cp -R ~/.config/bat         home/.config
    run cp -R ~/.config/fontconfig  home/.config
    run cp -R ~/.config/foot        home/.config
    run cp -R ~/.config/htop        home/.config
    run cp -R ~/.config/lf          home/.config
    run cp -R ~/.config/sway        home/.config

    # glirc config password check
    if grep -q 'sasl|password' ~/.config/glirc/config
    then echo >&2 'Password in ~/.config/glirc/config'
         echo >&2 'Not copying'
    else run cp -R ~/.config/glirc  home/.config
    fi
}

_load() {
    # TODO: Copy the files from this directory to the respective directories.
    #       Also, check before copying if the file exists already. If yes, show the diff
    #       to the user and ask if that file should be replaced/backed-up-and-replaced/kept.
    echo >&2 Not implemented yet
}

case "${1#dry_}" in
    (save) _save;;
    (load) _load;;
    (*) echo "Invalid command -- $1"
        echo "Run \"$(basename "$0") help\" for help"
        exit 1;;
esac

# vim: et ts=4 sts=4 sw=4 ft=sh
